"use client";

import type { Metadata } from "next";
import { usePathname } from "next/navigation";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname();
  const isLoginPage = ["/login", "/dashboard", "/dashboard/add-book"].includes(pathname);

  return (
    <html lang="en" suppressHydrationWarning>
      <body className="">
        {!isLoginPage ? (
          <main className="flex flex-col justify-between items-center h-[100vh]">
            <Navbar />
            <section className="flex w-fit gap-x-20">{children}</section>
            <Footer />
          </main>
        ) : (
          <>{children}</>
        )}
      </body>
    </html>
  );
}
