import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/navbar";
import Footer from "@/components/footer";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={``}
      >
        <main className="flex flex-col justify-between items-center h-[100vh] " >
          <Navbar></Navbar>
          <section className="flex w-fit gap-x-20" >
            {children}
          </section>
          <Footer></Footer>
        </main>

      </body>
    </html>
  );
}
